/**
 * Deterministic JSON -> Markdown mirror renderer.
 *
 * Content Schema v0.2 / Taxonomy v0.2: batch JSON is canonical and batch
 * Markdown is a generated review artifact. CI must fail when the checked-in
 * Markdown is not byte-for-byte identical to a fresh render.
 *
 * This is a TypeScript port of `tools/SOLID_STATE_CONTENT_TOOL_v0.1.py::render`
 * so the invariant is enforced by `npm test` without a Python dependency. The
 * Python tool remains the reference implementation; `tests/mirror.test.ts`
 * asserts both agree.
 *
 * NOTE: this module intentionally reads the raw JSON. No engine runtime code
 * loads the generated Markdown.
 */

interface RawSchedule {
  eventId: string;
  offsetYears: number;
  windowYears: number;
  priority: string;
  validityCondition: string;
}

interface RawVariant {
  when: string;
  text: { en: string; [key: string]: string };
  effects?: Record<string, number>;
  addFlags?: string[];
  removeFlags?: string[];
  setMaterialCommitment?: string;
  schedules?: RawSchedule[];
  endingId?: string;
  endingOverrides?: Record<string, string>;
}

interface RawEvent {
  id: string;
  channel: string;
  family: string;
  age: { min: number; max: number | null };
  selectionMode: string;
  weightClass: string;
  repeatPolicy: string;
  repeatCooldownYears: number;
  repeatMaxCount: number | null;
  routeTags?: string[];
  materialTags?: string[];
  include: string;
  exclude: string;
  variants: RawVariant[];
  designerNotes: string;
}

export interface RawBatch {
  batchId: string;
  version: string;
  notes?: string;
  events: RawEvent[];
}

/**
 * Reproduces `json.dumps(value, ensure_ascii=False, sort_keys=True)` for the
 * flat string/number maps used by `effects` and `endingOverrides`.
 */
function pythonJsonDumps(value: Record<string, string | number>): string {
  const keys = Object.keys(value).sort();
  const parts = keys.map((key) => `${JSON.stringify(key)}: ${JSON.stringify(value[key])}`);
  return `{${parts.join(', ')}}`;
}

/** Truthiness matching Python's: empty object/array/string are falsy. */
function isNonEmptyObject(value: Record<string, unknown> | undefined): boolean {
  return value !== undefined && Object.keys(value).length > 0;
}

function isNonEmptyArray(value: unknown[] | undefined): boolean {
  return value !== undefined && value.length > 0;
}

export function renderBatchMarkdown(data: RawBatch): string {
  const lines: string[] = [
    '<!-- AUTOGENERATED FROM JSON. DO NOT EDIT THIS MARKDOWN BY HAND. -->',
    `# SOLID STATE — Event Batch ${data.batchId.replace('EVENT_BATCH_', '')}`,
    `## Version ${data.version} — Generated review mirror`,
    '',
    `**Canonical source:** \`${data.batchId}_v${data.version}.json\` (filename may include project prefix)`,
    '',
    data.notes ?? '',
    '',
    `**Event count:** ${data.events.length}`,
    '',
    '## Events',
    '',
  ];

  for (const event of data.events) {
    const maxAge = event.age.max === null ? '∞' : String(event.age.max);
    const maxCount = event.repeatMaxCount === null ? '∞' : String(event.repeatMaxCount);
    lines.push(
      `### ${event.id}`,
      `**Channel / family:** \`${event.channel}\` / \`${event.family}\`  `,
      `**Age:** ${event.age.min}–${maxAge}  `,
      `**Mode:** \`${event.selectionMode}\` · **Weight:** \`${event.weightClass}\`  `,
      `**Repeat:** \`${event.repeatPolicy}\` · cooldown ${event.repeatCooldownYears}y · max ${maxCount}  `,
      `**Include:** \`${event.include}\`  `,
      `**Exclude:** \`${event.exclude}\``,
      '',
    );

    event.variants.forEach((variant, index) => {
      lines.push(`**Variant ${index + 1} — when \`${variant.when}\`**`);
      lines.push(`> ${variant.text.en}`);
      if (isNonEmptyObject(variant.effects)) {
        lines.push(`- Effects: \`${pythonJsonDumps(variant.effects!)}\``);
      }
      if (isNonEmptyArray(variant.addFlags)) {
        lines.push(`- Add flags: \`${variant.addFlags!.join(', ')}\``);
      }
      if (isNonEmptyArray(variant.removeFlags)) {
        lines.push(`- Remove flags: \`${variant.removeFlags!.join(', ')}\``);
      }
      if (variant.setMaterialCommitment) {
        lines.push(`- Material Commitment: \`${variant.setMaterialCommitment}\``);
      }
      for (const schedule of variant.schedules ?? []) {
        lines.push(
          `- Schedule: \`${schedule.eventId}\` +${schedule.offsetYears}y, ` +
            `window ${schedule.windowYears}y, priority \`${schedule.priority}\`, ` +
            `valid while \`${schedule.validityCondition}\``,
        );
      }
      if (variant.endingId) {
        lines.push(`- Ending: \`${variant.endingId}\``);
      }
      if (isNonEmptyObject(variant.endingOverrides)) {
        lines.push(`- Ending overrides: \`${pythonJsonDumps(variant.endingOverrides!)}\``);
      }
      lines.push('');
    });

    if (isNonEmptyArray(event.routeTags)) {
      lines.push(`**Route tags:** \`${event.routeTags!.join(', ')}\`  `);
    }
    if (isNonEmptyArray(event.materialTags)) {
      lines.push(`**Material tags:** \`${event.materialTags!.join(', ')}\`  `);
    }
    lines.push(`**Designer note:** ${event.designerNotes}`);
    lines.push('');
  }

  return lines.join('\n').replace(/\s+$/, '') + '\n';
}
