import type { ContentBundle } from '../engine/content/load.js';
import { VISIBLE_STATS, type VisibleStat } from '../engine/types.js';
import type { H2aArmTelemetry, StatSnapshot } from './h2aThresholdTelemetry.js';
import type { MetricsSummary } from './metrics.js';
import type { FactionSummary } from './phase1_3.js';
import { num, pct, table } from './report.js';

/**
 * Markdown renderer for the H2A threshold calibration.
 *
 * Separate from `report.ts` and from the Phase 1.1 experiment renderer on
 * purpose: this run must not repurpose or overwrite the historical Phase 1.1
 * report, and its telemetry is H2A-specific.
 *
 * The document reports measurements and mechanically checks each arm against
 * the review bands in the supplied plan. It does not select a profile, and the
 * written recommendation lives in the findings document it links to.
 */

export interface H2aArm {
  /** CURRENT_AUTHORED / LOW / MID / HIGH. */
  label: string;
  mode: string;
  note?: string;
  contentVersion: string;
  /** Null for the untouched control arm. */
  gatesRewritten: number | null;
  appliedThresholds: Record<string, number> | null;
  eventsWithoutGate: string[];
  metrics: MetricsSummary;
  factions: FactionSummary;
  telemetry: H2aArmTelemetry;
}

export interface H2aThresholdPayload {
  generatedAt: string;
  /** Fingerprint of the canonical corpus, before any reversible rewrite. */
  contentVersion: string;
  balanceVersion: string;
  matrixVersion: string;
  planVersion: string;
  planStatus: string;
  planPurpose: string;
  baseCorpus: string;
  baseSeed: string;
  runsPerArm: number;
  sampling: Record<string, string | number | boolean>;
  arms: H2aArm[];
  requiredCoreMetrics: string[];
  explicitlyNotRun: string[];
  retentionPolicy: { notDropped: boolean; note: string };
  methodologyNotes: string[];
}

const BUCKETS = ['18-24', '25-34', '35-44', '45-54', '55-64', '65+'] as const;

function bucketShare(metrics: MetricsSummary, band: string): number | null {
  const entry = metrics.endingAgeShareByTargetBucket.find((b) => b.band === band);
  return entry ? entry.observedShare : null;
}

function snapshot(telemetry: H2aArmTelemetry, label: string): StatSnapshot | undefined {
  return telemetry.statSnapshots.find((s) => s.label === label);
}

function shareAtLeast15(telemetry: H2aArmTelemetry, label: string, stat: VisibleStat): number | null {
  const found = snapshot(telemetry, label);
  return found ? found.byStat[stat].shareAtLeast15 : null;
}

function drift(telemetry: H2aArmTelemetry, label: string, stat: VisibleStat): number | null {
  const found = snapshot(telemetry, label);
  return found ? found.byStat[stat].meanDriftFromStart : null;
}

function largestBucket(metrics: MetricsSummary): string {
  let best = '—';
  let bestShare = -1;
  for (const band of BUCKETS) {
    const value = bucketShare(metrics, band) ?? 0;
    if (value > bestShare) {
      bestShare = value;
      best = band;
    }
  }
  return best;
}

/** Mechanical check of one arm against the plan's stated review bands. */
function reviewBandFlags(arm: H2aArm): string[] {
  const m = arm.metrics;
  const flags: string[] = [];
  const completion = m.completedRate;
  if (completion < 0.45) flags.push(`completion ${pct(completion)} below the 45–70% review band`);
  else if (completion > 0.7) flags.push(`completion ${pct(completion)} above the 45–70% review band`);
  const commitment = m.materialCommitmentRate;
  if (commitment < 0.45) flags.push(`commitment ${pct(commitment)} below the 45–70% review band`);
  else if (commitment > 0.7) flags.push(`commitment ${pct(commitment)} above the 45–70% review band`);
  const commitAge = arm.telemetry.commitmentTiming.mean;
  if (commitAge !== null && commitAge > 35) {
    flags.push(`mean commitment age ${num(commitAge)} above the early-30s preference`);
  }
  if (largestBucket(m) !== '25-34') flags.push(`largest ending bucket is ${largestBucket(m)}, not 25-34`);
  if (m.endingShare65Plus > 0.35) flags.push(`65+ still holds ${pct(m.endingShare65Plus)} of endings`);
  const factionShare = arm.factions.factionEndingShare;
  if (factionShare > 0.5) flags.push(`faction endings are ${pct(factionShare)} of completions`);
  const failures = m.guardrails.filter((g) => g.severity === 'failure');
  if (failures.length > 0) flags.push(`${failures.length} guardrail failure(s)`);
  return flags;
}

export function renderH2aThresholdReport(content: ContentBundle, payload: H2aThresholdPayload): string {
  const out: string[] = [];
  const arms = payload.arms;

  out.push('# SOLID STATE — H2A Threshold Calibration');
  out.push('');
  out.push('**Measurements only.** Generated by the headless engine from');
  out.push('`content/balance/SOLID_STATE_H2A_THRESHOLD_CALIBRATION_PLAN_v0.1.json`.');
  out.push('');
  out.push(payload.planPurpose);
  out.push('');
  out.push(
    'No threshold profile is selected or frozen here. Canonical FIX gates are never edited: LOW/MID/HIGH are ' +
      'applied through the retained reversible rewrite in `src/sim/experiments.ts`, in memory only. The written ' +
      'recommendation lives in [`docs/H2A_THRESHOLD_CALIBRATION_FINDINGS.md`](../docs/H2A_THRESHOLD_CALIBRATION_FINDINGS.md); ' +
      'decisions stay in [`docs/OPEN_QUESTIONS.md`](../docs/OPEN_QUESTIONS.md). This file is regenerated on every run.',
  );
  out.push('');
  out.push(
    table(
      ['Field', 'Value'],
      [
        ['Generated at', payload.generatedAt],
        ['Content fingerprint (canonical corpus)', `\`${payload.contentVersion}\``],
        ['Base corpus', payload.baseCorpus],
        ['Balance constants', `v${payload.balanceVersion}`],
        ['Experiment matrix (threshold values)', `v${payload.matrixVersion}`],
        ['Calibration plan', `v${payload.planVersion} (${payload.planStatus})`],
        ['Base seed', `\`${payload.baseSeed}\``],
        ['Runs per arm', String(payload.runsPerArm)],
        ['Arms', arms.map((a) => a.label).join(', ')],
        ['Total runs', String(payload.runsPerArm * arms.length)],
        ...Object.entries(payload.sampling).map(([key, value]) => [key, `\`${String(value)}\``]),
      ],
    ),
  );
  out.push('');
  out.push('### Method notes');
  out.push('');
  for (const note of payload.methodologyNotes) out.push(`- ${note}`);
  out.push('');
  out.push('Deliberately **not** run in this task (harness retained, not retired):');
  out.push('');
  for (const skipped of payload.explicitlyNotRun) out.push(`- ${skipped}`);
  out.push('');
  out.push(payload.retentionPolicy.note);
  out.push('');

  // -------------------------------------------------------------------------
  out.push('## 1. Four-arm headline comparison');
  out.push('');
  out.push('### 1a. Completion and ending-age shape');
  out.push('');
  out.push('Bucket shares are shares of **completed** runs.');
  out.push('');
  out.push(
    table(
      ['Arm', 'Completion', 'Nonterminal', ...BUCKETS, 'Largest', 'Median age'],
      arms.map((arm) => [
        `**${arm.label}**`,
        pct(arm.metrics.completedRate),
        pct(arm.metrics.nonterminalRate),
        ...BUCKETS.map((band) => pct(bucketShare(arm.metrics, band))),
        largestBucket(arm.metrics),
        num(arm.metrics.medianEndingAge, 0),
      ]),
    ),
  );
  out.push('');
  out.push('### 1b. Commitment, coverage, factions, fallback');
  out.push('');
  out.push(
    table(
      [
        'Arm',
        'Commitment',
        'Mean age',
        'Median age',
        'Ending coverage',
        'Faction-ending share',
        'Generic fallback 65+',
        'Lore fallback 65+',
      ],
      arms.map((arm) => {
        const late = arm.metrics.loreFallbackShareByAgeBandActive['65+'];
        return [
          `**${arm.label}**`,
          pct(arm.metrics.materialCommitmentRate),
          num(arm.telemetry.commitmentTiming.mean),
          num(arm.telemetry.commitmentTiming.median, 0),
          `${pct(arm.metrics.endingCoverageShare)} (${arm.metrics.distinctEndingsObserved}/${arm.metrics.distinctEndingsInRegistry})`,
          pct(arm.factions.factionEndingShare),
          pct(late?.genericShare ?? null),
          pct(late?.loreShare ?? null),
        ];
      }),
    ),
  );
  out.push('');
  out.push('### 1c. Visible-stat tails, drift and housing');
  out.push('');
  out.push(
    table(
      ['Arm', 'CHR>=15 @35', 'INT>=15 @35', 'CHR>=15 final', 'INT>=15 final', 'MNY drift (final)', 'SPR drift (final)', 'Housing repeat rate'],
      arms.map((arm) => [
        `**${arm.label}**`,
        pct(shareAtLeast15(arm.telemetry, 'age 35', 'CHR')),
        pct(shareAtLeast15(arm.telemetry, 'age 35', 'INT')),
        pct(shareAtLeast15(arm.telemetry, 'final', 'CHR')),
        pct(shareAtLeast15(arm.telemetry, 'final', 'INT')),
        num(drift(arm.telemetry, 'final', 'MNY'), 2),
        num(drift(arm.telemetry, 'final', 'SPR'), 2),
        pct(arm.telemetry.housing.share2Plus),
      ]),
    ),
  );
  out.push('');
  out.push(
    '`Housing repeat rate` is the share of **all** runs that saw two or more housing-tagged events. ' +
      'Per-run conditional repeat rates are in section 6.',
  );
  out.push('');

  // -------------------------------------------------------------------------
  out.push('## 2. Correctness counters');
  out.push('');
  out.push('All of these must be zero in every arm. They are failures, not balance warnings.');
  out.push('');
  out.push(
    table(
      [
        'Arm',
        'Pre-25 coverage defects',
        'Pre-25 generic fallback',
        'Illegal faction transitions',
        'Lifecycle collisions',
        'Personal events after exit',
        'Endings before 18',
        'Commitments before 18',
      ],
      arms.map((arm) => [
        `**${arm.label}**`,
        String(arm.metrics.coverageErrors),
        String(arm.metrics.pre25FallbackYears),
        String(arm.factions.illegalTransitionCount),
        String(arm.factions.illegalLifecycleStateCount),
        String(arm.factions.personalEventsAfterExitCount),
        String(arm.telemetry.earlyOutcomes.endingsBefore18),
        String(arm.telemetry.earlyOutcomes.materialCommitmentsBefore18),
      ]),
    ),
  );
  out.push('');

  // -------------------------------------------------------------------------
  out.push('## 3. Core metrics per arm');
  out.push('');
  for (const arm of arms) {
    const m = arm.metrics;
    out.push(`### ${arm.label}`);
    out.push('');
    out.push(
      table(
        ['Field', 'Value'],
        [
          ['Mode', arm.mode],
          ['Derived content fingerprint', `\`${arm.contentVersion}\``],
          ['FIX gates rewritten', arm.gatesRewritten === null ? 'none (canonical corpus)' : String(arm.gatesRewritten)],
          [
            'Applied thresholds',
            arm.appliedThresholds === null
              ? 'as authored'
              : Object.entries(arm.appliedThresholds)
                  .map(([gate, value]) => `${gate}=${value}`)
                  .join(', '),
          ],
          ['Runs', String(m.runs)],
          ['Completed / nonterminal', `${m.completed} / ${m.nonterminal}`],
          ['Endings per 1000 runs', num((m.completed / Math.max(m.runs, 1)) * 1000, 0)],
          ['Ending age mean / median / p10 / p90', `${num(m.averageEndingAge)} / ${num(m.medianEndingAge, 0)} / ${num(m.endingAgeP10, 0)} / ${num(m.endingAgeP90, 0)}`],
          [
            'Commitment age mean / median / p10 / p90',
            `${num(arm.telemetry.commitmentTiming.mean)} / ${num(arm.telemetry.commitmentTiming.median, 0)} / ` +
              `${num(arm.telemetry.commitmentTiming.p10, 0)} / ${num(arm.telemetry.commitmentTiming.p90, 0)}`,
          ],
          ['Mean FIX at commitment / at ending', `${num(m.meanFixAtCommitment)} / ${num(m.meanFixAtEnding)}`],
          ['Route entry / climax rate', `${pct(m.routeEntryRate)} / ${pct(m.routeClimaxRate)}`],
          ['Route abandonment (expired schedule) rate', pct(m.routeAbandonmentRate)],
          ['Expired schedules (total)', String(m.expiredScheduleCount)],
          ['Schedule displacements per run', num(m.scheduleDisplacementPerRun, 3)],
          ['Priority collision rate', pct(m.priorityCollisionRate)],
          ['Generic fallback share (25+)', pct(m.fallbackShareAge25Plus)],
          ['Lore fallback share (all years)', pct(m.loreFallbackShare)],
          ['Material entropy (bits)', num(m.materialEntropyBitsOverall, 3)],
          ['Faction endings (sudden / committed ladder)', `${arm.factions.suddenFactionEndings} / ${arm.factions.committedLadderFactionEndings}`],
        ],
      ),
    );
    out.push('');
    out.push('**Ending-age buckets**');
    out.push('');
    out.push(
      table(
        ['Bucket', 'Endings', 'Share of all runs', 'Share of completed', 'Target band', 'Within target'],
        content.balance.targetEndingAgeShare.map((target) => {
          const band = target.maxAge === null ? `${target.minAge}+` : `${target.minAge}-${target.maxAge}`;
          const count = m.endingAgeHistogram[band] ?? 0;
          const entry = m.endingAgeShareByTargetBucket.find((b) => b.band === band);
          return [
            band,
            String(count),
            pct(m.runs === 0 ? 0 : count / m.runs),
            pct(entry?.observedShare ?? null),
            `${pct(target.minShare, 0)}–${pct(target.maxShare, 0)}`,
            entry?.withinTarget ? 'yes' : 'no',
          ];
        }),
      ),
    );
    out.push('');
    out.push('**Endings by route family**');
    out.push('');
    const families = Object.entries(m.endingCountsByRouteFamily).sort((a, b) => b[1] - a[1]);
    if (families.length === 0) {
      out.push('_No endings observed._');
    } else {
      out.push(
        table(
          ['Route family', 'Endings', 'Share of completions', 'Median age'],
          families.map(([family, count]) => [
            `\`${family}\``,
            String(count),
            pct(m.completed === 0 ? 0 : count / m.completed),
            num(m.endingAgeByRouteFamily[family]?.median ?? null, 0),
          ]),
        ),
      );
    }
    out.push('');
    out.push('**Ending ID distribution**');
    out.push('');
    const endings = Object.entries(m.endingDistribution).sort((a, b) => b[1] - a[1]);
    if (endings.length === 0) {
      out.push('_No endings observed._');
    } else {
      out.push(
        table(
          ['Ending', 'Title', 'Runs', 'Share of completions'],
          endings.map(([endingId, count]) => [
            `\`${endingId}\``,
            content.endings.get(endingId)?.title_en ?? '—',
            String(count),
            pct(m.completed === 0 ? 0 : count / m.completed),
          ]),
        ),
      );
    }
    out.push('');
    out.push('**Final material distribution**');
    out.push('');
    out.push(
      table(
        ['Material', 'Runs', 'Share'],
        Object.entries(m.finalMaterialDistribution)
          .sort((a, b) => b[1] - a[1])
          .map(([material, count]) => [material, String(count), pct(count / Math.max(m.runs, 1))]),
      ),
    );
    out.push('');
    const warnings = m.guardrails;
    out.push('**Guardrail findings**');
    out.push('');
    if (warnings.length === 0) out.push('_None._');
    else {
      out.push(
        table(
          ['Severity', 'ID', 'Finding'],
          warnings.map((g) => [g.severity.toUpperCase(), `\`${g.id}\``, g.message]),
        ),
      );
    }
    out.push('');
    if (arm.eventsWithoutGate.length > 0) {
      out.push(`_Gate-assigned events with no FIX gate to rewrite: ${arm.eventsWithoutGate.join(', ')}._`);
      out.push('');
    }
  }

  // -------------------------------------------------------------------------
  out.push('## 4. Visible-stat telemetry');
  out.push('');
  out.push(
    'Fixed-age snapshots are taken **entering** that age and include only runs still active then; the active ' +
      'count is the denominator on every row. `start` is the post-setup baseline and is the reference for drift. ' +
      'Visible stats are unclamped in the canonical balance constants and nothing here clamps them.',
  );
  out.push('');
  for (const arm of arms) {
    out.push(`### ${arm.label}`);
    out.push('');
    for (const snap of arm.telemetry.statSnapshots) {
      out.push(`**${snap.label}** — active runs: ${snap.activeRuns}`);
      out.push('');
      out.push(
        table(
          ['Stat', 'N', 'Mean', 'Median', 'p10', 'p25', 'p75', 'p90', 'p95', 'Min', 'Max', '<=2', '<=4', '>=12', '>=15', '>=20', 'Drift'],
          VISIBLE_STATS.map((stat) => {
            const d = snap.byStat[stat];
            return [
              stat,
              String(d.activeRuns),
              num(d.mean, 2),
              num(d.median, 1),
              num(d.p10, 0),
              num(d.p25, 0),
              num(d.p75, 0),
              num(d.p90, 0),
              num(d.p95, 0),
              num(d.min, 0),
              num(d.max, 0),
              pct(d.shareAtMost2),
              pct(d.shareAtMost4),
              pct(d.shareAtLeast12),
              pct(d.shareAtLeast15),
              pct(d.shareAtLeast20),
              num(d.meanDriftFromStart, 2),
            ];
          }),
        ),
      );
      out.push('');
    }
    out.push('**Authored deltas per 1 000 run-years, and final vs. post-setup start**');
    out.push('');
    const drifts = arm.telemetry.statDrift;
    out.push(
      table(
        ['Stat', '+ deltas /1k yr', '+ magnitude /1k yr', '- deltas /1k yr', '- magnitude /1k yr', 'Final lower', 'Final equal', 'Final higher'],
        VISIBLE_STATS.map((stat) => [
          stat,
          num(drifts.positiveDeltaEventsPer1000RunYears[stat], 1),
          num(drifts.positiveDeltaMagnitudePer1000RunYears[stat], 1),
          num(drifts.negativeDeltaEventsPer1000RunYears[stat], 1),
          num(drifts.negativeDeltaMagnitudePer1000RunYears[stat], 1),
          pct(drifts.finalVsStart[stat].lowerShare),
          pct(drifts.finalVsStart[stat].equalShare),
          pct(drifts.finalVsStart[stat].higherShare),
        ]),
      ),
    );
    out.push('');
  }

  // -------------------------------------------------------------------------
  out.push('## 5. Event frequency');
  out.push('');
  out.push(
    'Top events by occurrence. `Repeat rate` is the share of runs that saw the event which saw it more than once.',
  );
  out.push('');
  for (const arm of arms) {
    out.push(`### ${arm.label} — top ${arm.telemetry.topEvents.length} of ${arm.telemetry.distinctEventsObserved} distinct events observed`);
    out.push('');
    out.push(
      table(
        ['Event', 'Text', '/1k run-yr', 'Run incidence', 'Repeat rate', 'Mean when seen', 'Max in one run', 'Repeat policy'],
        arm.telemetry.topEvents.map((row) => [
          `\`${row.eventId}\``,
          excerpt(row.label),
          num(row.occurrencesPer1000RunYears, 1),
          pct(row.runIncidence),
          pct(row.repeatWithinRunRate),
          num(row.meanCountWhereSeen, 2),
          String(row.maxCountInOneRun),
          row.repeatPolicy === 'repeatable'
            ? `repeatable (cooldown ${row.repeatCooldownYears}, max ${row.repeatMaxCount ?? '∞'})`
            : 'once per run',
        ]),
      ),
    );
    out.push('');
  }

  // -------------------------------------------------------------------------
  out.push('## 6. Housing');
  out.push('');
  out.push(
    'Housing events are identified by the canonical route tag `housing` in the Route Tag Registry, not by English ' +
      'text and not by a single hard-coded event ID.',
  );
  out.push('');
  out.push(`Tagged events: ${arms[0]?.telemetry.housing.eventIds.map((id) => `\`${id}\``).join(', ') ?? 'none'}.`);
  out.push('');
  out.push(
    table(
      ['Arm', 'Runs with any', 'Occurrences /1k run-yr', 'Runs with 2+', '2+ share of all runs', 'Mean when seen', 'Max in one run'],
      arms.map((arm) => {
        const h = arm.telemetry.housing;
        return [
          `**${arm.label}**`,
          `${h.runsWithAny} (${pct(h.runIncidence)})`,
          num(h.occurrencesPer1000RunYears, 1),
          String(h.runsWith2Plus),
          pct(h.share2Plus),
          num(h.meanCountWhereSeen, 2),
          String(h.maxCountInOneRun),
        ];
      }),
    ),
  );
  out.push('');
  for (const arm of arms) {
    const h = arm.telemetry.housing;
    out.push(`**${arm.label}** — housing occurrences by event, and authored visible-stat deltas they carry`);
    out.push('');
    out.push(
      table(
        ['Event', 'Occurrences'],
        Object.entries(h.countsByEventId)
          .sort((a, b) => b[1] - a[1])
          .map(([id, count]) => [`\`${id}\``, String(count)]),
      ),
    );
    out.push('');
    out.push(
      table(
        ['Stat', 'Total delta', 'Mean per housing event', 'Mean per run with housing'],
        VISIBLE_STATS.map((stat) => [
          stat,
          num(h.statDeltaTotals[stat], 0),
          num(h.meanStatDeltaPerHousingEvent[stat], 3),
          num(h.meanStatDeltaPerRunWithHousing[stat], 3),
        ]),
      ),
    );
    out.push('');
  }

  // -------------------------------------------------------------------------
  out.push('## 7. Low-stat conditional risk');
  out.push('');
  out.push(
    'Person-year analysis from age 18. Each observed year is classified by the stat value **entering** that year, ' +
      'then followed forward. A person-year counts toward a horizon only when its follow-up is complete: the run ' +
      'either reached an ending, or was still being simulated at `age + horizon`. Person-years censored by the ' +
      'diagnostic maximum age are dropped rather than counted as "no event". Commitment and faction-COMMITTED ' +
      'probabilities are conditioned on that outcome not having happened yet, so their denominators differ.',
  );
  out.push('');
  out.push('**This is correlation, not causation, and no danger weighting is implemented.**');
  out.push('');
  for (const arm of arms) {
    out.push(`### ${arm.label}`);
    out.push('');
    for (const stat of VISIBLE_STATS) {
      const rows = arm.telemetry.lowStatRisk.byStat[stat];
      out.push(`**${stat}**`);
      out.push('');
      out.push(
        table(
          ['Band', 'Person-years', 'Horizon', 'Observed', 'P(ending)', 'Uncommitted N', 'P(commitment)', 'No-faction N', 'P(faction COMMITTED)'],
          rows.flatMap((row) =>
            row.horizons.map((h, index) => [
              index === 0 ? `${row.band} (${row.condition})` : '',
              index === 0 ? String(row.personYears) : '',
              `${h.horizonYears}y`,
              String(h.observedPersonYears),
              pct(h.endingProbability),
              String(h.commitmentEligiblePersonYears),
              pct(h.commitmentProbability),
              String(h.factionCommittedEligiblePersonYears),
              pct(h.factionCommittedProbability),
            ]),
          ),
        ),
      );
      out.push('');
    }
  }

  // -------------------------------------------------------------------------
  out.push('## 8. Faction-chain legibility');
  out.push('');
  out.push(
    'Attribution uses canonical `factionIds` / `factionInteraction` metadata. A **personalized touchpoint** is an ' +
      'event addressed to the player by that faction — interaction `contact`, `personal` or `climax`. News ' +
      'bulletins and lore fallback are world texture and are excluded. "First disposition" is the first lifecycle ' +
      'move after CONTACTED; "escalation after ENGAGED" is any later personalized touchpoint; "climax after ' +
      'COMMITTED" is a `climax` event at or after the COMMITTED transition.',
  );
  out.push('');
  for (const arm of arms) {
    out.push(`### ${arm.label}`);
    out.push('');
    out.push(
      table(
        ['Faction', 'Contact', 'ENGAGED', 'COMMITTED', 'OPTED_OUT', 'CLOSED', 'Endings'],
        arm.telemetry.factionChains.map((row) => [
          row.shortName,
          `${row.contactRuns} (${pct(row.contactRate)})`,
          pct(row.everReachedRate['ENGAGED'] ?? 0),
          pct(row.everReachedRate['COMMITTED'] ?? 0),
          pct(row.everReachedRate['OPTED_OUT'] ?? 0),
          pct(row.everReachedRate['CLOSED'] ?? 0),
          `${row.endingRuns} (${pct(row.endingRate)})`,
        ]),
      ),
    );
    out.push('');
    out.push(
      table(
        ['Faction', 'Touchpoints: 1', '2', '3+', 'Mean', 'Mean gap (yr)', 'Median gap', 'Exit at first disposition', 'Escalation after ENGAGED', 'Climax after COMMITTED'],
        arm.telemetry.factionChains.map((row) => {
          const contacted = Math.max(row.contactRuns, 1);
          return [
            row.shortName,
            pct(row.personalizedEventBuckets.one / contacted),
            pct(row.personalizedEventBuckets.two / contacted),
            pct(row.personalizedEventBuckets.threePlus / contacted),
            num(row.meanPersonalizedEventsPerContactedRun, 2),
            num(row.meanGapYears, 2),
            num(row.medianGapYears, 1),
            `${pct(row.firstDispositionExitShare)} (n=${row.firstDispositionRuns})`,
            `${pct(row.escalationAfterEngagedShare)} (n=${row.escalationAfterEngagedRuns})`,
            `${pct(row.climaxAfterCommittedShare)} (n=${row.climaxAfterCommittedRuns})`,
          ];
        }),
      ),
    );
    out.push('');
  }

  // -------------------------------------------------------------------------
  out.push('## 9. Review-band check');
  out.push('');
  out.push(
    'Mechanical comparison against the review bands stated in the calibration plan and review guide. These are ' +
      '**review bands, not final game targets**, and a flag is a discussion point, not a rejection. Nothing here ' +
      'selects a profile.',
  );
  out.push('');
  out.push(
    table(
      ['Arm', 'Flags'],
      arms.map((arm) => {
        const flags = reviewBandFlags(arm);
        return [`**${arm.label}**`, flags.length === 0 ? 'none' : flags.join('; ')];
      }),
    ),
  );
  out.push('');
  out.push(
    'The written recommendation — which arm, if any, is plausible as a provisional H2A profile, and the ' +
      'material/faction/stat tradeoffs — is in ' +
      '[`docs/H2A_THRESHOLD_CALIBRATION_FINDINGS.md`](../docs/H2A_THRESHOLD_CALIBRATION_FINDINGS.md). ' +
      'It is analysis only: no profile is written into content, no threshold is interpolated, and Q-27 stays open ' +
      'until design reviews this calibration.',
  );
  out.push('');

  out.push('## 10. Required core metrics checklist');
  out.push('');
  for (const metric of payload.requiredCoreMetrics) out.push(`- ${metric}`);
  out.push('');

  return out.join('\n');
}

function excerpt(text: string, limit = 60): string {
  const flat = text.replace(/\s+/g, ' ').trim();
  const cut = flat.length <= limit ? flat : `${flat.slice(0, limit - 1)}…`;
  return cut.replace(/\|/g, '\\|');
}
