#!/usr/bin/env python3
"""
SOLID STATE content consistency tool.

Canonical source: event batch JSON.
Generated review artifact: event batch Markdown.

Usage:
  python SOLID_STATE_CONTENT_TOOL_v0.3.py render BATCH.json [OUTPUT.md]
  python SOLID_STATE_CONTENT_TOOL_v0.3.py check  BATCH.json BATCH.md
  python SOLID_STATE_CONTENT_TOOL_v0.3.py validate BATCH.json

`check` exits non-zero if Markdown is not byte-for-byte identical to a fresh render.

v0.3 (Phase 1.3, Content Schema v0.4): the generated review mirror now shows the
new faction metadata (`factionIds`, `factionInteraction`) and every variant
`factionTransitions` entry, rather than silently omitting them. Validation also
covers the `lore_fallback_only` selection mode, whose whole point is that it can
have no mechanical effect.
"""
from __future__ import annotations
import json, re, sys
from pathlib import Path

ID_RE = re.compile(r"^EVT-(ORD|INS|TRN|SPC)-[A-Z0-9]+-\d{4}$")
VALID_MODES = {"random","scheduled_only","mandatory_only","climax","fallback_only","lore_fallback_only"}
VALID_INTERACTIONS = {"contact","personal","climax","news","lore_fallback"}
VALID_LIFECYCLE_TARGETS = {"CONTACTED","ENGAGED","COMMITTED","OPTED_OUT","CLOSED"}
FACTION_ID_RE = re.compile(r"^FCT-[A-Z0-9-]+$")
VALID_REPEAT = {"once_per_run","repeatable"}
VALID_WEIGHTS = {"VERY_LOW","LOW","NORMAL","HIGH","VERY_HIGH"}

def load(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))

def render(data):
    lines = [
        "<!-- AUTOGENERATED FROM JSON. DO NOT EDIT THIS MARKDOWN BY HAND. -->",
        f"# SOLID STATE — Event Batch {data['batchId'].replace('EVENT_BATCH_','')}",
        f"## Version {data['version']} — Generated review mirror",
        "",
        f"**Canonical source:** `{data['batchId']}_v{data['version']}.json` (filename may include project prefix)",
        "",
        data.get("notes",""),
        "",
        f"**Event count:** {len(data['events'])}",
        "",
        "## Events",
        "",
    ]
    for e in data["events"]:
        max_age = "∞" if e["age"]["max"] is None else e["age"]["max"]
        max_count = "∞" if e["repeatMaxCount"] is None else e["repeatMaxCount"]
        lines += [
            f"### {e['id']}",
            f"**Channel / family:** `{e['channel']}` / `{e['family']}`  ",
            f"**Age:** {e['age']['min']}–{max_age}  ",
            f"**Mode:** `{e['selectionMode']}` · **Weight:** `{e['weightClass']}`  ",
            f"**Repeat:** `{e['repeatPolicy']}` · cooldown {e['repeatCooldownYears']}y · max {max_count}  ",
            f"**Include:** `{e['include']}`  ",
            f"**Exclude:** `{e['exclude']}`",
            "",
        ]
        for i,v in enumerate(e["variants"],1):
            lines.append(f"**Variant {i} — when `{v['when']}`**")
            lines.append(f"> {v['text']['en']}")
            if v.get("effects"):
                lines.append(f"- Effects: `{json.dumps(v['effects'], ensure_ascii=False, sort_keys=True)}`")
            if v.get("addFlags"):
                lines.append(f"- Add flags: `{', '.join(v['addFlags'])}`")
            if v.get("removeFlags"):
                lines.append(f"- Remove flags: `{', '.join(v['removeFlags'])}`")
            for t in v.get("factionTransitions",[]):
                line = f"- Faction transition: `{t['factionId']}` -> `{t['to']}`"
                if t.get("removeRoles"):
                    line += f", remove roles `{', '.join(t['removeRoles'])}`"
                if t.get("addRoles"):
                    line += f", add roles `{', '.join(t['addRoles'])}`"
                lines.append(line)
            if v.get("setMaterialCommitment"):
                lines.append(f"- Material Commitment: `{v['setMaterialCommitment']}`")
            for s in v.get("schedules",[]):
                priority_order = f", priorityOrder {s['priorityOrder']}" if "priorityOrder" in s else ""
                lines.append(
                    f"- Schedule: `{s['eventId']}` +{s['offsetYears']}y, "
                    f"window {s['windowYears']}y, priority `{s['priority']}`"
                    f"{priority_order}, valid while `{s['validityCondition']}`"
                )
            if v.get("endingId"):
                lines.append(f"- Ending: `{v['endingId']}`")
            if v.get("endingOverrides"):
                lines.append(f"- Ending overrides: `{json.dumps(v['endingOverrides'], ensure_ascii=False, sort_keys=True)}`")
            lines.append("")
        if e.get("routeTags"):
            lines.append(f"**Route tags:** `{', '.join(e['routeTags'])}`  ")
        if e.get("materialTags"):
            lines.append(f"**Material tags:** `{', '.join(e['materialTags'])}`  ")
        if e.get("refinementTags"):
            lines.append(f"**Refinement tags:** `{', '.join(e['refinementTags'])}`  ")
        if e.get("factionIds"):
            lines.append(f"**Factions:** `{', '.join(e['factionIds'])}`  ")
        if e.get("factionInteraction"):
            lines.append(f"**Faction interaction:** `{e['factionInteraction']}`  ")
        lines.append(f"**Designer note:** {e['designerNotes']}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"

def validate(data):
    errors = []
    ids = []
    for i,e in enumerate(data.get("events",[])):
        loc = f"events[{i}]"
        eid = e.get("id","")
        ids.append(eid)
        if not ID_RE.match(eid):
            errors.append(f"{loc}: malformed id {eid!r}")
        if e.get("selectionMode") not in VALID_MODES:
            errors.append(f"{eid}: invalid selectionMode")
        if e.get("weightClass") not in VALID_WEIGHTS:
            errors.append(f"{eid}: invalid weightClass")
        if e.get("repeatPolicy") not in VALID_REPEAT:
            errors.append(f"{eid}: invalid repeatPolicy")
        if not isinstance(e.get("repeatCooldownYears"), int) or e["repeatCooldownYears"] < 0:
            errors.append(f"{eid}: repeatCooldownYears must be integer >=0")
        mc = e.get("repeatMaxCount")
        if mc is not None and (not isinstance(mc,int) or mc < 1):
            errors.append(f"{eid}: repeatMaxCount must be integer >=1 or null")
        if e.get("repeatPolicy") == "once_per_run" and mc != 1:
            errors.append(f"{eid}: once_per_run must have repeatMaxCount=1")
        if e.get("selectionMode") == "fallback_only":
            if e.get("age",{}).get("min",0) < 25:
                errors.append(f"{eid}: fallback_only is forbidden before age 25")
            if e.get("repeatPolicy") != "repeatable":
                errors.append(f"{eid}: fallback_only must be repeatable")
        # Content Schema v0.4: lore fallback is world texture and nothing else.
        if e.get("selectionMode") == "lore_fallback_only":
            if e.get("age",{}).get("min",0) < 25:
                errors.append(f"{eid}: lore_fallback_only is forbidden before age 25")
            if e.get("repeatPolicy") != "repeatable":
                errors.append(f"{eid}: lore_fallback_only must be repeatable")
            for vi,v in enumerate(e.get("variants",[]),1):
                where = f"{eid} variant {vi}"
                if v.get("effects"):
                    errors.append(f"{where}: lore_fallback_only may not change stats")
                if v.get("addFlags") or v.get("removeFlags"):
                    errors.append(f"{where}: lore_fallback_only may not change flags")
                if v.get("factionTransitions"):
                    errors.append(f"{where}: lore_fallback_only may not change faction state")
                if v.get("schedules"):
                    errors.append(f"{where}: lore_fallback_only may not schedule events")
                if v.get("setMaterialCommitment"):
                    errors.append(f"{where}: lore_fallback_only may not commit material")
                if v.get("endingId"):
                    errors.append(f"{where}: lore_fallback_only may not produce an ending")
        # Content Schema v0.4 faction metadata.
        interaction = e.get("factionInteraction")
        if interaction is not None and interaction not in VALID_INTERACTIONS:
            errors.append(f"{eid}: invalid factionInteraction {interaction!r}")
        faction_ids = e.get("factionIds") or []
        for fid in faction_ids:
            if not FACTION_ID_RE.match(fid):
                errors.append(f"{eid}: malformed factionId {fid!r}")
        if interaction is not None and not faction_ids:
            errors.append(f"{eid}: factionInteraction without factionIds")
        for vi,v in enumerate(e.get("variants",[]),1):
            seen_factions = set()
            for t in v.get("factionTransitions",[]):
                where = f"{eid} variant {vi}"
                fid = t.get("factionId","")
                if not FACTION_ID_RE.match(fid):
                    errors.append(f"{where}: malformed transition factionId {fid!r}")
                if t.get("to") not in VALID_LIFECYCLE_TARGETS:
                    errors.append(f"{where}: invalid transition target {t.get('to')!r}")
                if fid and fid not in faction_ids:
                    errors.append(f"{where}: transitions {fid}, which is not in the event's factionIds")
                if fid in seen_factions:
                    errors.append(f"{where}: transitions {fid} more than once")
                seen_factions.add(fid)
        variants = e.get("variants",[])
        if not variants:
            errors.append(f"{eid}: must have at least one variant")
        elif variants[-1].get("when") != "TRUE":
            errors.append(f"{eid}: final variant should be TRUE fallback")
        amin = e.get("age",{}).get("min")
        amax = e.get("age",{}).get("max")
        if not isinstance(amin,int) or amin < 0:
            errors.append(f"{eid}: invalid minimum age")
        if amax is not None and (not isinstance(amax,int) or amax < amin):
            errors.append(f"{eid}: invalid maximum age")
        # v1 childhood safety: any event eligible entirely/partly under 18 must not author commitment/ending.
        if amin is not None and amin < 18:
            for vi,v in enumerate(variants):
                if v.get("setMaterialCommitment"):
                    errors.append(f"{eid} variant {vi+1}: material commitment forbidden under-18-capable event")
                if v.get("endingId"):
                    errors.append(f"{eid} variant {vi+1}: canonical ending forbidden under-18-capable event")
    if len(ids) != len(set(ids)):
        errors.append("duplicate event IDs present")
    known = set(ids)
    for e in data.get("events",[]):
        for v in e.get("variants",[]):
            for s in v.get("schedules",[]):
                # Cross-batch refs are allowed, so warn only by convention? Here same-batch absence is not error.
                if s.get("offsetYears",0) < 1:
                    errors.append(f"{e['id']}: scheduled offsetYears must be >=1")
                po = s.get("priorityOrder", 0)
                if not isinstance(po, int):
                    errors.append(f"{e['id']}: schedule priorityOrder must be an integer")
    return errors

def main(argv):
    if len(argv) < 3:
        raise SystemExit(__doc__)
    cmd = argv[1]
    data = load(argv[2])
    errors = validate(data)
    if errors:
        print("VALIDATION FAILED", file=sys.stderr)
        for e in errors:
            print(" -", e, file=sys.stderr)
        raise SystemExit(2)
    if cmd == "validate":
        print(f"OK: {len(data['events'])} events validated")
        return
    generated = render(data)
    if cmd == "render":
        out = Path(argv[3]) if len(argv) >= 4 else Path(argv[2]).with_suffix(".md")
        out.write_text(generated, encoding="utf-8")
        print(out)
        return
    if cmd == "check":
        if len(argv) < 4:
            raise SystemExit("check requires JSON and Markdown paths")
        md = Path(argv[3])
        actual = md.read_text(encoding="utf-8")
        if actual != generated:
            print(f"MISMATCH: {md} is not the deterministic render of {argv[2]}", file=sys.stderr)
            raise SystemExit(3)
        print(f"OK: {md.name} exactly matches canonical JSON")
        return
    raise SystemExit(f"unknown command: {cmd}")

if __name__ == "__main__":
    main(sys.argv)
